"""add foto_url to kits_festa

Revision ID: 076089392d0d
Revises: 69378a91efb4
Create Date: 2026-03-17 10:47:03.392489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076089392d0d'
down_revision: Union[str, Sequence[str], None] = '69378a91efb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kits_festa', sa.Column('foto_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kits_festa', 'foto_url')
    # ### end Alembic commands ###
