"""add registros aluguel and remove cliente from kit

Revision ID: 2f2a478552d0
Revises: 946793545ff3
Create Date: 2026-03-17 13:42:41.569575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f2a478552d0'
down_revision: Union[str, Sequence[str], None] = '946793545ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_alugueis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('kit_id', sa.UUID(), nullable=False),
    sa.Column('data_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_recebimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_cobrado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pagamento_status', sa.String(length=50), nullable=True),
    sa.Column('pagamento_metodo', sa.String(length=50), nullable=True),
    sa.Column('condicao_entrega', sa.String(length=100), nullable=True),
    sa.Column('condicao_recebimento', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits_festa.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_alugueis_cliente_id'), 'registros_alugueis', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_registros_alugueis_kit_id'), 'registros_alugueis', ['kit_id'], unique=False)
    op.create_index(op.f('ix_registros_alugueis_tenant_id'), 'registros_alugueis', ['tenant_id'], unique=False)
    op.drop_table('client_kits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_kits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('kit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clientes.id'], name=op.f('client_kits_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kit_id'], ['kits_festa.id'], name=op.f('client_kits_kit_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('client_kits_pkey')),
    sa.UniqueConstraint('client_id', 'kit_id', name=op.f('uq_client_kit'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_registros_alugueis_tenant_id'), table_name='registros_alugueis')
    op.drop_index(op.f('ix_registros_alugueis_kit_id'), table_name='registros_alugueis')
    op.drop_index(op.f('ix_registros_alugueis_cliente_id'), table_name='registros_alugueis')
    op.drop_table('registros_alugueis')
    # ### end Alembic commands ###
