"""add tabela clientes

Revision ID: 946793545ff3
Revises: b92f6bf84171
Create Date: 2026-03-17 13:27:44.916974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '946793545ff3'
down_revision: Union[str, Sequence[str], None] = 'b92f6bf84171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('cpf', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('clientes', sa.Column('quantidade_alugueis', sa.Integer(), nullable=False))
    op.add_column('clientes', sa.Column('aluguel_em_curso', sa.Boolean(), nullable=False))
    op.add_column('clientes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_cliente_tenant_telefone'), 'clientes', type_='unique')
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=False)
    op.create_index(op.f('ix_clientes_tenant_id'), 'clientes', ['tenant_id'], unique=False)
    op.drop_column('clientes', 'email')
    op.drop_column('clientes', 'criado_em')
    op.drop_column('clientes', 'observacoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('observacoes', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('clientes', sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clientes_tenant_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf'), table_name='clientes')
    op.create_unique_constraint(op.f('uq_cliente_tenant_telefone'), 'clientes', ['tenant_id', 'telefone'], postgresql_nulls_not_distinct=False)
    op.drop_column('clientes', 'created_at')
    op.drop_column('clientes', 'aluguel_em_curso')
    op.drop_column('clientes', 'quantidade_alugueis')
    op.drop_column('clientes', 'saldo')
    op.drop_column('clientes', 'cpf')
    # ### end Alembic commands ###
